### PR TITLE
Feature/3 transfer

### PR DESCRIPTION
**Pull request by egisan**
Implemented Transfer between accounts
Implemented Tests according to specs
Implemented controls and error messages

(this time the PR is towards the correct branch :-) 

Please Jens, check it out.

### CODE REVIEW

**Comment by JensMHe** [comment]
When you enter  wrong format of the money you want to transfer you get two diffrent error messages displayed. Maybe one is enough.

**Comment by egisan** [comment]
Performed requested changes. Please check :)

**Comment by JensMHe** [comment]
It looks fine now!

**Review by JensMHe — APPROVED** [review]
Looks good!

**Pull request merged**
