### PR TITLE
Added customer and account information to index page

### PR DESCRIPTION
**Pull request by JensMHe**
Merging feature branch to develop branch

### CODE REVIEW

**Comment by JensMHe** [comment]
Kolla över min feature branch merge med min develop branch, tack.

**Comment by egisan** [comment]
Hej Jens, I reviewed your code. Here are my comments:
1) Index view: Add a header like "Customer account list" or something like that. Move the table some row below
:-)

**Comment by egisan** [comment]
2. One more thing: in Index View the Account numbers must be unique

**Comment by JensMHe** [comment]
Done!

**Pull request merged**
